import 'package:flutter/material.dart';

class ColorsRes {
  /// Main colors
  static const primary = Color(0xFFFFF5F7);
  static const secondary = Color(0XCCFF6A92);
  static const contentLightTheme = Color(0xFF1D1D35);
  static const contentDarkTheme = Color(0xFFF5FCF9);
  static const backgroundTheme = Color(0xFFFFDFE8);
  static const backgroundThemeOld = Color(0X33FF7FAC);
  static const warning = Color(0xFFF1DC3E);
  static const error = Color(0xFFF03738);
  static const pinkCard = Color(0xFFFFB5B5);
  static const greenCard = Color(0xFFABFFA9);
  static const blueCard = Color(0xFFA1EEFF);
  static const yellowCard = Color(0xFFFFF386);
  static const lightPink = Color(0xFFFFBFD7);
  static const blackText = Color(0xFF2B2B2B);

  static const pinkWhite = Color(0xFFFDF3F6);

  /// Common colors
  static const black = Color(0xFF2B2B2B);
  static const black0 = Color(0xFF000000);
  static const black2B = Color(0xFF2B2B2B);
  static const white = Colors.white;
  static const blue = Color(0xFF3497FD);
  static const orange = Color(0xFFFD960A);
  static const yellow = Color(0xFFFFAD00);
  static const red = Color(0xFFFF003D);
  static const pink = Color(0xFFFC7FAC);
  static const green = Color(0xFF00C257);
  static const palePink = Color(0xFFFEC3D7);
  static const bgPink = Color(0xFFFFEAF2);
  static const bgPink2 = Color(0xFFFFEFF5);
  static const transparent = Colors.transparent;
  static const black12 = Color(0x1F000000);
  static const black54 = Color(0x8A000000);
  static const black87 = Color(0xDD000000);
  static const gray50 = Color(0xFFFAFAFA);
  static const gray100 = Color(0xFFF5F5F5);
  static const gray200 = Color(0xFFEEEEEE);
  static const gray300 = Color(0xFFE0E0E0);
  static const lightGray1 = Color(0xFFE5E5E5);
  static const lightGray2 = Color(0xFFC4C4C4);
  static const lightGray3 = Color(0xFFE3E3E3);
  static const darkGray = Color(0xFF8A8A8A);
  static const hover = Color(0xFFF5F5F5);
  static const backgroundGray = Color(0xFFEEEEEE);
  static const backgroundItem = Color(0xFFEFEEEE);
  static const backgroundGray2 = Color(0xFFCCCCCC);
  static const backgroundBlue = Color(0xFF39A9EE);

  /// Widget colors
  static const buttonDisable = Color(0xFFCFCFCF);
  static const textGray = Color(0xFFB3B3B3);
  static const textDisable = Color(0xFFADADAD);
  static const borderList = Color(0xFFE8E8E8);
  static const shadow = Color(0xFFD9D9D9);
  static const bottomSheetTitle = Color(0xFF32CD32);
  static const inputTextField = Color(0xFF1D232E);
  static const borderFieldColor = Color(0xFFE8E8E8);
  static const titleLoginColor = Color(0XFF808080);
  static const borderSwitch = Color(0xFF2E3A59);
  static const snackBarError = Color(0xFFFF0000);
  static const borderGray = Color(0XFFD9D9D9);
  static const bgLightYellow = Color(0XFFFFFEDB);
  static const inactive = Color(0xFFD3D3D4);
  static const pinkTap = Color(0xFFEB688E);
  static const pinkDefault = Color(0xFFFC0358);
  static const stepColor = Color(0XFFA1E0E2);
  static const darkGreen = Color(0XFF2EB993);
  static const buttonPinkDisable = Color(0XFFFFBFD7);
  static const hintColor = Color(0xFFCFCFCF);
  static const selectionColor = Color(0xFFF0F0F0);
  static const lightYellow = Color(0xFFFFFEDB);
  static const errorText = Color(0xFFFF4747);
  static const textBlack = Color(0xFF333333);
  static const grayDisable = Color(0xFFF9F9F9);
  static const shadowColor = Color(0xFFBFBFBF);
  static const blueColor = Color(0xFF45BCFF);
  static const blueColor1 = Color(0xFF38A9EE);
  static const lightPink1 = Color(0xFFFFE7EF);
  static const accentColor = Color(0xFF00FFFF);
  static const defaultDropdown = Color(0xFFA9BBCE);
  static const selectionColor1 = Color(0xFF7B848A);
  static const yellowDefault = Color(0xFFFEF286);
  static const blueDefault = Color(0xFF9FEBFC);
  static const redDefault = Color(0xFFE85252);
  static const linkDefault = Color(0xFF0096C7);
  static const textfieldBorder = Color(0xFFCCCCCC);
  static const textfieldCounterText = Color(0x99000000);
  static const textfieldMarkRequired = Color(0xFFFB0E0E);
  static const blueButtonText = Color(0xFF44AFFF);
  static const backgroundGrey = Color(0xFFC9C9C9);
  static const tabBarRed = Color(0xFFF80E0E);
  static const redButton = Color(0xFFd13f3d);
  static const requestPhotoPermissionBodyText = Color(0xFF6fb2e1);
  static const requestPhotoPermissionDivider = Color(0xFFe4e4e4);
  static const requestPhotoPermissionCancelText = Color(0xFF1a75eb);
}
